#!/usr/bin/env bash
# Copy-and-carry every third-party dependency into vendor/ as a pinned source
# snapshot. No FetchContent, no package manager, no build-time downloads.
#
# Rationale (see MANIFEST.md §4): a pinned SHA guarantees integrity, not
# availability; and -Werror against a compiler newer than upstream CI may
# require patching a third-party source in place.
#
# Knobs are constants below. No argument parsing.
set -euo pipefail

readonly REPO_ROOT="/Users/whom/dvel/ghzhub/GR4-fork/gnuradio4-womm"
readonly VENDOR_DIR="${REPO_ROOT}/vendor"
readonly LOCK_FILE="${VENDOR_DIR}/MANIFEST.lock"

# name | url | ref
#
# libsoundio is pinned to master, deliberately NOT to the newer-looking
# 2.0.1-* tags: those live on the zig-pkg branch and do NOT contain master's
# 2023 CoreAudio fix (kAudioObjectPropertyElementMaster -> ...Main).
readonly DEPS=(
  "boost-ut|https://github.com/boost-ext/ut.git|53e17f25119598c6458d30351b260193096ba67e"
  "vir-simd|https://github.com/mattkretz/vir-simd.git|v0.4.4"
  "cpp-httplib|https://github.com/yhirose/cpp-httplib.git|v0.18.1"
  "cpr|https://github.com/libcpr/cpr.git|1.14.1"
  "libsoundio|https://github.com/andrewrk/libsoundio.git|49a1f78b50eb0f5a49d096786a95a93874a2592a"
  # Both Soapy pins are master commits, NOT the newest release tags.
  #   SoapyUHD 0.4.1 (2020) predates UHD 4.8 and would not build against our
  #   UHD 4.10; master adds post_input_action/post_output_action for UHD 4.8+,
  #   newer-CMake compat, and the C++14 the UHD headers require.
  #   SoapySDR 0.8.1 (2021) lacks the macOS rpath fix and the os-x-clang fix.
  # Copy-and-carry pins an exact SHA either way, so tag-vs-branch is not the
  # safety property here. Note master moves SOAPY_SDR_ABI_VERSION 0.8 -> 0.8-3:
  # harmless while we build every module ourselves, but a prebuilt third-party
  # module compiled against "0.8" will refuse to load.
  "SoapySDR|https://github.com/pothosware/SoapySDR.git|1551ea0d39ce546b32a15808b9b1241018a89fc8"
  "SoapyUHD|https://github.com/pothosware/SoapyUHD.git|2a5d381f68fd05d5b3c0e7db56c36892ea99b4ae"
)

# assert we are where we think we are
[[ -f "${REPO_ROOT}/CLAUDE.md" && -d "${REPO_ROOT}/core/include/gnuradio-4.0" ]] || {
  echo "FATAL: ${REPO_ROOT} is not the gnuradio4 root" >&2; exit 1; }

mkdir -p "${VENDOR_DIR}"
: > "${LOCK_FILE}"
{
  echo "# vendor/MANIFEST.lock - generated by scripts/vendor.sh"
  echo "# name  ref  resolved_sha  tree_sha256  files  bytes"
} >> "${LOCK_FILE}"

for entry in "${DEPS[@]}"; do
  IFS='|' read -r name url ref <<< "${entry}"
  dest="${VENDOR_DIR}/${name}"
  printf '\n=== %s @ %s ===\n' "${name}" "${ref}"
  rm -rf "${dest}"
  mkdir -p "${dest}"

  # fetch exactly one commit; works for both tags and raw SHAs
  git -C "${dest}" init -q
  git -C "${dest}" remote add origin "${url}"
  GIT_TERMINAL_PROMPT=0 git -C "${dest}" fetch -q --depth 1 origin "${ref}"
  git -C "${dest}" checkout -q FETCH_HEAD
  sha="$(git -C "${dest}" rev-parse HEAD)"

  # strip history: we carry the source, not the upstream repo
  rm -rf "${dest}/.git"

  # deterministic digest over file contents and paths
  tree_sha="$(cd "${dest}" && find . -type f -print0 | sort -z \
              | xargs -0 shasum -a 256 | shasum -a 256 | cut -d' ' -f1)"
  files="$(find "${dest}" -type f | wc -l | tr -d ' ')"
  bytes="$(du -sk "${dest}" | cut -f1)"

  printf '%s  %s  %s  %s  %s  %sKiB\n' \
    "${name}" "${ref}" "${sha}" "${tree_sha}" "${files}" "${bytes}" >> "${LOCK_FILE}"
  printf 'resolved %s  (%s files, %s KiB)\n' "${sha}" "${files}" "${bytes}"

  # licence must travel with the code
  if ! ls "${dest}" | grep -qiE '^(LICENSE|COPYING|LICENCE)'; then
    echo "WARNING: no LICENSE file at root of ${name}" >&2
  fi
done

printf '\n=== lock file ===\n'
cat "${LOCK_FILE}"

# Vendored trees MUST be force-added.
#
# Two independent sets of ignore rules would otherwise silently drop files:
#   1. gnuradio4's own .gitignore - "lib/" alone swallows the entire
#      vendor/SoapySDR/lib/ core implementation, leaving an unbuildable
#      snapshot; "Makefile", "bin/", ".vscode/" and "build*/" hit others.
#   2. .gitignore files inside the vendored repositories themselves, which
#      take precedence over root rules and so cannot be un-ignored from here.
#
# -f bypasses both. Once tracked, files are no longer subject to ignore rules.
cat <<'NOTE'

NEXT: git add -f vendor      (plain `git add vendor` silently drops ~59 files)
      then verify with:      scripts/verify-vendor.sh
NOTE
